project:
  type: website

website:
  title: "Samantha Moon DSAN 5000"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.ipynb

format:
  html:
    theme: cosmo
    toc: true



